POST http://localhost:5000/device/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njg5ODg2NzQsInN1YiI6OH0.pdQUHMgGA74zaV42BbNLzjWgVkMbj9WMsP8FiEzcrzg

{
    "name": "livingroom sensor",
    "ident": "sensor_0",
    "csv_location": "/home/stefan/Documents/Projects/licenta/tests/telemetry/living.csv",
    "visibility": true
}