POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "stefan",
    "password": "parola"
}

###

POST http://localhost:5000/automation/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM1MzgyNjYsInN1YiI6NH0.ASK7MVxg7TvAXmBYFzrjwbN7mTkiWv8hzpNOnrrR1V0
Content-Type: application/json

{
    "name": "open_light",
    "content": "ifnightopenlight"
}

###

POST http://localhost:5000/automation/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM1MzgyNjYsInN1YiI6NH0.ASK7MVxg7TvAXmBYFzrjwbN7mTkiWv8hzpNOnrrR1V0
Content-Type: application/json

{
    "name": "window_close",
    "content": "ifco2>2000openwindow"
}

###
GET  http://localhost:5000/automation/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM1MzgyNjYsInN1YiI6NH0.ASK7MVxg7TvAXmBYFzrjwbN7mTkiWv8hzpNOnrrR1V0

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "passwrod1234"
}

###

POST http://localhost:5000/automation/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM1Mzg2NTgsInN1YiI6NX0.ykyx2wqKIDEw1sItuD4EeY2zRKKS-SITCFWPEbEeU5o
Content-Type: application/json

{
    "name": "close_door",
    "content": "ifnohumanclosedoor"
}

###

GET http://localhost:5000/automation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM1Mzg2NTgsInN1YiI6NX0.ykyx2wqKIDEw1sItuD4EeY2zRKKS-SITCFWPEbEeU5o